# Generated by Django 3.1.4 on 2020-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201215_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='travelitem',
            name='time_made',
        ),
        migrations.AddField(
            model_name='registry',
            name='time_made',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
