# Generated by Django 3.1.4 on 2020-12-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201215_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelItem',
            new_name='Item',
        ),
    ]
