# Generated by Django 3.1.4 on 2020-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201215_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fulfilled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_donor',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_foster',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
