# Generated by Django 3.1.4 on 2020-12-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201215_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.registry'),
        ),
    ]
