# Generated by Django 3.1.4 on 2020-12-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201217_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('requestedItems', 'requestedItems'), ('inProgress', 'inProgress'), ('fulfilled', 'fulfilled')], default='requestedItems', max_length=15),
        ),
    ]
