# Generated by Django 3.1.4 on 2020-12-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fulfilled',
        ),
    ]
