# Generated by Django 3.1.4 on 2020-12-30 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registries', to=settings.AUTH_USER_MODEL),
        ),
    ]
