# Generated by Django 3.1.5 on 2021-01-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201230_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_foster',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=255)),
                ('time_made', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.URLField()),
                ('from_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
