# Generated by Django 3.1.5 on 2021-01-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210106_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='to_user',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='from_user',
            new_name='sender',
        ),
    ]
